/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatronageRouteImport } from './routes/patronage'
import { Route as EditionsProductIdRouteImport } from './routes/editions_.$productId'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronageRoute = PatronageRouteImport.update({
  id: '/patronage',
  path: '/patronage',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsProductIdRoute = EditionsProductIdRouteImport.update({
  id: '/editions_/$productId',
  path: '/editions/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/editions/$productId': typeof EditionsProductIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/editions/$productId': typeof EditionsProductIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/editions_/$productId': typeof EditionsProductIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/editions/$productId'
    | '/order/$orderId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/editions/$productId'
    | '/order/$orderId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/editions_/$productId'
    | '/order/$orderId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  EditionsRoute: typeof EditionsRoute
  GalleryRoute: typeof GalleryRoute
  LibraryRoute: typeof LibraryRoute
  LineageRoute: typeof LineageRoute
  LoginRoute: typeof LoginRoute
  PatronageRoute: typeof PatronageRoute
  EditionsProductIdRoute: typeof EditionsProductIdRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patronage': {
      id: '/patronage'
      path: '/patronage'
      fullPath: '/patronage'
      preLoaderRoute: typeof PatronageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions_/$productId': {
      id: '/editions_/$productId'
      path: '/editions/$productId'
      fullPath: '/editions/$productId'
      preLoaderRoute: typeof EditionsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  EditionsRoute: EditionsRoute,
  GalleryRoute: GalleryRoute,
  LibraryRoute: LibraryRoute,
  LineageRoute: LineageRoute,
  LoginRoute: LoginRoute,
  PatronageRoute: PatronageRoute,
  EditionsProductIdRoute: EditionsProductIdRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
