/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatronageRouteImport } from './routes/patronage'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as EditionsProductIdRouteImport } from './routes/editions_.$productId'
import { Route as LibrarySlugRouteImport } from './routes/library_.$slug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as VaultRoomRouteImport } from './routes/vault_.$room'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiShopCatalogRouteImport } from './routes/api/shop/catalog'
import { Route as ApiShopCheckoutRouteImport } from './routes/api/shop/checkout'
import { Route as ApiShopStatusRouteImport } from './routes/api/shop/status'
import { Route as ApiShopWebhookRouteImport } from './routes/api/shop/webhook'
import { Route as ApiShopOrderOrderIdRouteImport } from './routes/api/shop/order.$orderId'
import { Route as ApiShopPrintifyProductsRouteImport } from './routes/api/shop/printify/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronageRoute = PatronageRouteImport.update({
  id: '/patronage',
  path: '/patronage',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsProductIdRoute = EditionsProductIdRouteImport.update({
  id: '/editions_/$productId',
  path: '/editions/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library_/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoomRoute = VaultRoomRouteImport.update({
  id: '/vault_/$room',
  path: '/vault/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCatalogRoute = ApiShopCatalogRouteImport.update({
  id: '/api/shop/catalog',
  path: '/api/shop/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCheckoutRoute = ApiShopCheckoutRouteImport.update({
  id: '/api/shop/checkout',
  path: '/api/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopStatusRoute = ApiShopStatusRouteImport.update({
  id: '/api/shop/status',
  path: '/api/shop/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopWebhookRoute = ApiShopWebhookRouteImport.update({
  id: '/api/shop/webhook',
  path: '/api/shop/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopOrderOrderIdRoute = ApiShopOrderOrderIdRouteImport.update({
  id: '/api/shop/order/$orderId',
  path: '/api/shop/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopPrintifyProductsRoute = ApiShopPrintifyProductsRouteImport.update({
  id: '/api/shop/printify/products',
  path: '/api/shop/printify/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/vault': typeof VaultRoute
  '/editions/$productId': typeof EditionsProductIdRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/vault/$room': typeof VaultRoomRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/catalog': typeof ApiShopCatalogRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/shop/webhook': typeof ApiShopWebhookRoute
  '/api/shop/order/$orderId': typeof ApiShopOrderOrderIdRoute
  '/api/shop/printify/products': typeof ApiShopPrintifyProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/vault': typeof VaultRoute
  '/editions/$productId': typeof EditionsProductIdRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/vault/$room': typeof VaultRoomRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/catalog': typeof ApiShopCatalogRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/shop/webhook': typeof ApiShopWebhookRoute
  '/api/shop/order/$orderId': typeof ApiShopOrderOrderIdRoute
  '/api/shop/printify/products': typeof ApiShopPrintifyProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/editions': typeof EditionsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/lineage': typeof LineageRoute
  '/login': typeof LoginRoute
  '/patronage': typeof PatronageRoute
  '/vault': typeof VaultRoute
  '/editions_/$productId': typeof EditionsProductIdRoute
  '/library_/$slug': typeof LibrarySlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/vault_/$room': typeof VaultRoomRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/catalog': typeof ApiShopCatalogRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/shop/webhook': typeof ApiShopWebhookRoute
  '/api/shop/order/$orderId': typeof ApiShopOrderOrderIdRoute
  '/api/shop/printify/products': typeof ApiShopPrintifyProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/vault'
    | '/editions/$productId'
    | '/library/$slug'
    | '/order/$orderId'
    | '/vault/$room'
    | '/api/auth/$'
    | '/api/shop/catalog'
    | '/api/shop/checkout'
    | '/api/shop/status'
    | '/api/shop/webhook'
    | '/api/shop/order/$orderId'
    | '/api/shop/printify/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/vault'
    | '/editions/$productId'
    | '/library/$slug'
    | '/order/$orderId'
    | '/vault/$room'
    | '/api/auth/$'
    | '/api/shop/catalog'
    | '/api/shop/checkout'
    | '/api/shop/status'
    | '/api/shop/webhook'
    | '/api/shop/order/$orderId'
    | '/api/shop/printify/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/editions'
    | '/gallery'
    | '/library'
    | '/lineage'
    | '/login'
    | '/patronage'
    | '/vault'
    | '/editions_/$productId'
    | '/library_/$slug'
    | '/order/$orderId'
    | '/vault_/$room'
    | '/api/auth/$'
    | '/api/shop/catalog'
    | '/api/shop/checkout'
    | '/api/shop/status'
    | '/api/shop/webhook'
    | '/api/shop/order/$orderId'
    | '/api/shop/printify/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  EditionsRoute: typeof EditionsRoute
  GalleryRoute: typeof GalleryRoute
  LibraryRoute: typeof LibraryRoute
  LineageRoute: typeof LineageRoute
  LoginRoute: typeof LoginRoute
  PatronageRoute: typeof PatronageRoute
  VaultRoute: typeof VaultRoute
  EditionsProductIdRoute: typeof EditionsProductIdRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  VaultRoomRoute: typeof VaultRoomRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShopCatalogRoute: typeof ApiShopCatalogRoute
  ApiShopCheckoutRoute: typeof ApiShopCheckoutRoute
  ApiShopStatusRoute: typeof ApiShopStatusRoute
  ApiShopWebhookRoute: typeof ApiShopWebhookRoute
  ApiShopOrderOrderIdRoute: typeof ApiShopOrderOrderIdRoute
  ApiShopPrintifyProductsRoute: typeof ApiShopPrintifyProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patronage': {
      id: '/patronage'
      path: '/patronage'
      fullPath: '/patronage'
      preLoaderRoute: typeof PatronageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions_/$productId': {
      id: '/editions_/$productId'
      path: '/editions/$productId'
      fullPath: '/editions/$productId'
      preLoaderRoute: typeof EditionsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$slug': {
      id: '/library_/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault_/$room': {
      id: '/vault_/$room'
      path: '/vault/$room'
      fullPath: '/vault/$room'
      preLoaderRoute: typeof VaultRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/catalog': {
      id: '/api/shop/catalog'
      path: '/api/shop/catalog'
      fullPath: '/api/shop/catalog'
      preLoaderRoute: typeof ApiShopCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/checkout': {
      id: '/api/shop/checkout'
      path: '/api/shop/checkout'
      fullPath: '/api/shop/checkout'
      preLoaderRoute: typeof ApiShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/status': {
      id: '/api/shop/status'
      path: '/api/shop/status'
      fullPath: '/api/shop/status'
      preLoaderRoute: typeof ApiShopStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/webhook': {
      id: '/api/shop/webhook'
      path: '/api/shop/webhook'
      fullPath: '/api/shop/webhook'
      preLoaderRoute: typeof ApiShopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/order/$orderId': {
      id: '/api/shop/order/$orderId'
      path: '/api/shop/order/$orderId'
      fullPath: '/api/shop/order/$orderId'
      preLoaderRoute: typeof ApiShopOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/printify/products': {
      id: '/api/shop/printify/products'
      path: '/api/shop/printify/products'
      fullPath: '/api/shop/printify/products'
      preLoaderRoute: typeof ApiShopPrintifyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  EditionsRoute: EditionsRoute,
  GalleryRoute: GalleryRoute,
  LibraryRoute: LibraryRoute,
  LineageRoute: LineageRoute,
  LoginRoute: LoginRoute,
  PatronageRoute: PatronageRoute,
  VaultRoute: VaultRoute,
  EditionsProductIdRoute: EditionsProductIdRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  VaultRoomRoute: VaultRoomRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShopCatalogRoute: ApiShopCatalogRoute,
  ApiShopCheckoutRoute: ApiShopCheckoutRoute,
  ApiShopStatusRoute: ApiShopStatusRoute,
  ApiShopWebhookRoute: ApiShopWebhookRoute,
  ApiShopOrderOrderIdRoute: ApiShopOrderOrderIdRoute,
  ApiShopPrintifyProductsRoute: ApiShopPrintifyProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
